### ISSUE TITLE
table pdf exports with line

### ISSUE THREAD

**Issue by priyatharsan** [plotly/orca#147]
related to https://github.com/plotly/streambed/issues/11618

The issue still seems to persist in few environments. The PDF exports display line in the following environments: 
user at intercom:  Windows 10 / Chrome viewer
@priyatharsan Windows 10 / Adobe-reader
@nicolaskruchten MacOS10.13 / Chrome70

It did not show any lines in: MacOS10.13 / Preview

Example plots: https://plot.ly/python/table/#row-color-based-on-variable
https://plot.ly/python/table/#alternating-row-colors
Please note: 
- the plot was tested by recreating them in the respective environments
- also, the rest of the plots in https://plot.ly/python/table did not display any lines in the exported PDF in the above mentioned environments

**Comment by etpinard** [comment]
Can you try opening 

[fig.pdf](https://github.com/plotly/orca/files/2586673/fig.pdf)

on whichever platform that is still showing erroneous lines?

**Comment by priyatharsan** [comment]
I don't see the line in this pdf used Adobe reader

**Comment by etpinard** [comment]
Here's the output of

```
./bin/orca.js graph https://plot.ly/~jordanpeterson/410.json --format pdf
```

[fig.pdf](https://github.com/plotly/orca/files/2586749/fig.pdf)

No erroneous lines in `evince` nor in the Chrome PDF viewer.

**Comment by etpinard** [comment]
Already, we'll looks like this isn't a problem with orca nor with plotly.js. Something must be up with our prod image server machine. Can someone confirm that they are all using `plotly.js@1.42.5`?

**Comment by priyatharsan** [comment]
how do I test that?

**Comment by priyatharsan** [comment]
https://github.com/plotly/plotly.py/blob/master/js/package.json#L34
I think the issue is specific to python API.

**Comment by priyatharsan** [comment]
Do we have any updates regarding this issue?

**Comment by etpinard** [comment]
No updates. Nothing makes me believe this problems has to do with orca or plotly.js.

**Comment by etpinard** [comment]
@priyatharsan I'll close this ticket

The latest version of orca, plotly.py and plotly.js are able to export that `table` graph w/o the erroneous line

**Comment by priyatharsan** [comment]
@etpinard  Thanks for the update 👍

**Comment by vishalsharma3003** [comment]
I had the same problem and there is not much information provided. I don't know the exact reason why the erroneous line is there in these graphs but I have a workaround for this.
Try setting the background color of the graph and you'll notice that the line is aligned with the background so I adjusted the margins and put the right margin to zero and the problem was resolved.

layout(margin = list(r = 0, pad = 0)) 

Before:
![image](https://user-images.githubusercontent.com/19642193/75415325-50bce080-5951-11ea-99fd-953650b5203c.png)

After:
![image](https://user-images.githubusercontent.com/19642193/75415307-46024b80-5951-11ea-83b2-80a2b17a5766.png)
