### ISSUE TITLE
Compatibility with Alpine (Docker)

### ISSUE THREAD

**Issue by TiemenSch** [plotly/orca#183]
I'm having trouble getting orca to work on an Alpine Docker image. 

I used frolvlad's glibc image to install miniconda: https://hub.docker.com/r/frolvlad/alpine-glibc/
and then installed orca using conda.

At first, it was missing some dependencies, but I got stuck after it told me to relink some of the ``.so`` files.

This may be the usual suspect where musl and glibc libraries end up in an unhappy marriage, but I would love to get orca to work on Alpine!

**Comment by antoinerg** [comment]
Hello @TiemenSch! Thank you for your interest in Orca.

Orca is an Electron application so it runs a Chromium browser. It goes without saying that it has a lot of dependencies because of this. Even by starting with Alpine, the resulting image will still be a few hundred megabytes at least. Anyway, could you share your Dockerfile so I can assist you? Finally, would you see value in us providing an official Docker image for Orca?

**Comment by TiemenSch** [comment]
Hi @antoinerg!

For me the value would lie in case in a JupyterLab(Hub) deployment where the user's container is based on an Alpine Docker image and headless mode is required. 

I could of course switch to an Ubuntu based image and try making it work that way, but would rather stick with Alpine. 

In short, headless mode, but with Alpine for minimum size.

A good not too custom place to start would be 
frolvlad/alpine-miniconda3:python3.6

**Comment by TiemenSch** [comment]
OK, after a night's sleep I switched from Alpine to Ubuntu. Turns out my Docker image size was getting significantly larger anyways, which makes the ~50MB size difference no longer outweigh the ease of use you get with Ubuntu.

I would suggest to close this as any other better "headless" option than running an X-server has a good chance to fix this one, too.
