### ISSUE TITLE
plotly.py was unable to communicate local orca server process

### ISSUE THREAD

**Issue by anuragpal** [plotly/orca#244]
Hi Everyone,

    I am using plotly. When I am using plotly 
    fig.write_image(img, width=1920, height=1440)

     I am getting error like:
 
     For some reason plotly.py was unable to communicate with the
local orca server process, even though the server process seems to be running.

Please review the process and connection information below:

orca status
-----------
    state: running
    executable: /usr/bin/xvfb-run --auto-servernum --server-args -screen 0 640x480x24 +extension RANDR +extension GLX /root/.nvm/versions/node/v10.1.0/bin/orca
    version: 1.2.1
    port: 45043
    pid: 2471
    command: ['/usr/bin/xvfb-run', '--auto-servernum', '--server-args', '-screen 0 640x480x24 +extension RANDR +extension GLX', '/root/.nvm/versions/node/v10.1.0/bin/orca', 'serve', '-p', '45043', '--plotly', '/root/cuantafy_generator/venv/lib/python3.6/site-packages/plotly/package_data/plotly.min.js', '--graph-only', '--mathjax', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js', '--mapbox-access-token', 'map-key']

plotly.io.orca.ensure_server()
        time.sleep(10)

I have already tested this is any other solution, I can implement.

Help is really appreciated

**Comment by gree0299** [comment]
Hey mate I had a similar issue not too long ago. What figure are you trying to write? 

Also have you tried anything from issue #241? I posted my solutions for the issue in that thread so it is worth trying that if you havent

**Comment by anuragpal** [comment]
Thanks for your reply, 

   When I debug the script the problem is large set of data due to which ocra stopped responding, when I pass less data its working smoothly. So might be I have to check how to to manage it for large data set. If you have suggestion for that it will really help me.

**Comment by gree0299** [comment]
No worries mate, it is worth checking the issue I linked in the first comment as there is some stuff you can try which might help.

If you just want to test to see if it works - open a command line and manually launch an Orca server but make sure you specify the --keepalive option which will ensure the server relaunches if it crashes. If this doesn't fix it, try the same command but instead of --keepalive specify the --debug option and note whatever errors it logs. Just keep in mind, when using the --keepalive option it doesn't kill failed Orca processes so you will need to manually kill them.

**Comment by antoinerg** [comment]
> When I debug the script the problem is large set of data due to which ocra stopped responding, when I pass less data its working smoothly.

It seems the problem described here is related to exporting images with lots of points. Therefore, I will close it in favor of #240.
