### ISSUE TITLE
How to use it on Windows

### ISSUE THREAD

**Issue by markzolotoy** [plotly/orca#287]
It says: Extract the windows-release.zip file. I dont see in the downloaded zip file. So, how do I make it work on Windows?

Thanks

**Comment by antoinerg** [comment]
@markzolotoy the zip files are available in the `release` page. The one you are looking for has this URL: https://github.com/plotly/orca/releases/download/v1.2.1/windows-release.zip.

Once unzipped, you will find an installer with filename `orca Setup 1.2.1.exe`.

Please let me know if you have any troubles or otherwise close the issuse :smile_cat:

**Comment by markzolotoy** [comment]
Yea, I see it, thanks.
