### ISSUE TITLE
how to deploy orca in kubernetes

### ISSUE THREAD

**Issue by devopsdymyr** [plotly/orca#304]
i have tried to deploy orca in kubernetes but not working Any suggestion how to expose pod to external with help of ingress or loadbalancer

**Comment by antoinerg** [comment]
Hello @devopsdymyr,

We are not officially supporting/documenting K8s deployment at the moment but it should be possible to do so since we already ship a Docker image (https://quay.io/repository/plotly/orca).

Closing this one unless something is problematic with our Docker image. Feel free to reopen if that is the case.
