### ISSUE TITLE
text attribute appears on bar traces with plotly.js 2.0

### ISSUE THREAD

**Issue by cpsievert** [plotly/orca#374]
Bumping plotly.js  from 1.58.4 to 2.0.0 with latest release of orca (1.3.1) introduces a regression where the `text` attribute now appears on `bar` traces:    

```shell
cd ~/tmp
wget https://cdn.plot.ly/plotly-1.58.4.min.js ./
orca graph '{ "data": [ { "x": [1, 2], "y": [10, 11.5], "text": ["cond: control<br />result: 10.0", "cond: treatment<br />result: 11.5"], "type": "bar" } ] }' -o before.png --plotly plotly-1.58.4.min.js 
open before.png
```

![before](https://user-images.githubusercontent.com/1365941/121252181-551ebb80-c86d-11eb-9c96-c03740c10109.png)

```shell
wget https://cdn.plot.ly/plotly-2.0.0.min.js ./
orca graph '{ "data": [ { "x": [1, 2], "y": [10, 11.5], "text": ["cond: control<br />result: 10.0", "cond: treatment<br />result: 11.5"], "type": "bar" } ] }' -o after.png --plotly plotly-2.0.0.min.js 
open after.png
```

![after](https://user-images.githubusercontent.com/1365941/121252295-6ff13000-c86d-11eb-93fd-668e2d65d109.png)

**Comment by antoinerg** [comment]
cc @archmoj @nicolaskruchten

**Comment by archmoj** [comment]
This is the expected behaviour in plotly.js v2. 
Related PR: https://github.com/plotly/plotly.js/pull/5638
In order to drop text on bars, the `textposition` could be set to *"none"* similar to other traces.

**Comment by nicolaskruchten** [comment]
Correct. The rationale here was that setting `text` should be enough to actually have `text` appear, whereas previously it would only appear in the hoverlabel, controlled via `hoverinfo`. The recommended thing to do now if you want stuff in the hoverlabel is to use `hovertemplate` (possibly in conjunction with `customdata` but that's optional ofc). In general this leads to smaller figures due to less repetition of values in `text`.

**Comment by cpsievert** [comment]
Ah ok, that's fair. For some reason I thought the static export had different behavior but I goofed up versions, thanks!
