### ISSUE TITLE
Test AppVeyor Windows executable on a Windows machine

### ISSUE THREAD

**Issue by etpinard** [plotly/orca#70]
PR https://github.com/plotly/image-exporter/pull/63 added a build step for Windows on AppVeyor. 

Unfortunately, no one has had the time to test it out yet.

**Comment by n-riesco** [comment]
For the record (it may be a red herring though): when I ran the windows executable with `--verbose`, the dev console had an error message `Uncaught SyntaxError: invalid unicode escape sequence`.

**Comment by JamesCropcho** [comment]
@n-riesco If you ran it on Windows: I wager it's important and useful. If you ran it not on Windows, I'd wager it's a red herring.

**Comment by n-riesco** [comment]
@JamesCropcho To be clear: I run the windows executable on a windows machine. :smiley_cat:

**Comment by JamesCropcho** [comment]
@n-riesco Yeah, I was pretty sure you were running it in a Windows environment, but I wanted to one hundred percent sure. Also, the specific error message you described sounds like the flavor associated with executable-environment mismatch.

Interesting, I do not get output matching yours:

```
Microsoft Windows [Version 10.0.16299.371]
(c) 2017 Microsoft Corporation. All rights reserved.                                                                                                                                                                                            C:\Users\James>"C:\Users\James\AppData\Local\Programs\image-exporter\Plotly Graph Exporter.exe" --verbose
C:\Users\James>
(node:204) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: no valid input given
(node:204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                                                                                                                                              

C:\Users\James>                                                                                                          
```

(The `UnhandledPromiseRejectionWarning` was showing up previously, too, when zero arguments were attached, so one may disregard that.)

I wonder if it's because we have different versions of Windows.

And/or, it may matter that I am still using yesterday's executable, in case something changed since then.

**Comment by etpinard** [comment]
Fixed by https://github.com/plotly/orca/pull/88/commits/63e54345fe48d9b90572e55655239c1599e5a2a7

(at least, on @dy's Windows 7 laptop)
